Repository SalmanActivity/salman-activity-backend, pull requests merged in 2018-03, with the labels that each got.

#1 Test/location crud
  location/crud.js
  location/crud.spec.js
Labels: test

#2 Test/user crud
  crud/get.js
  user/crud.js
  user/crud.spec.js
Labels: test

#5 fix auth endpoint
  app.js
  auth/index.js
  user/index.js
Labels: refactor

#6 Bugfix/fix user division reference
  crud/post.js
  user/crud.js
  user/crud.spec.js
  user/user.js
Labels: bug

#8 Test/request crud
  auth/auth.js
  auth/auth.spec.js
  crud/put.js
  package-lock.json
  package.json
  request/crud.js
  request/crud.test.js
  request/request.js
  scripts/seed_db.js
  seed.js
Labels: test
